# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: wheelhouse/v1/core.proto, wheelhouse/v1/skills.proto, wheelhouse/v1/stream.proto, wheelhouse/v1/system.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import Dict

import betterproto


@dataclass(eq=False, repr=False)
class TextMessage(betterproto.Message):
    """TextMessage — plain text content published into a stream."""

    content: str = betterproto.string_field(1)
    publisher_id: str = betterproto.string_field(2)
    timestamp_ms: int = betterproto.int64_field(3)
    user_id: str = betterproto.string_field(4)
    """
    User ID referencing a registered UserProfile (FR59).
     Present when message is from a human user via a surface; empty for agent messages.
    """

    reply_to_user_id: str = betterproto.string_field(5)
    """
    Target user ID for response routing (FR59).
     Set by agents when responding to a specific user.
     Surfaces use this to route responses to the correct chat/session.
    """


@dataclass(eq=False, repr=False)
class FileMessage(betterproto.Message):
    """FileMessage — binary or file content published into a stream."""

    filename: str = betterproto.string_field(1)
    mime_type: str = betterproto.string_field(2)
    data: bytes = betterproto.bytes_field(3)
    publisher_id: str = betterproto.string_field(4)
    timestamp_ms: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class Reaction(betterproto.Message):
    """Reaction — a lightweight reaction to a stream object."""

    target_object_id: str = betterproto.string_field(1)
    emoji: str = betterproto.string_field(2)
    publisher_id: str = betterproto.string_field(3)
    timestamp_ms: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class SkillInvocation(betterproto.Message):
    """SkillInvocation — request to invoke a skill, published by an agent."""

    skill_name: str = betterproto.string_field(1)
    agent_id: str = betterproto.string_field(2)
    invocation_id: str = betterproto.string_field(3)
    parameters: Dict[str, str] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    timestamp_ms: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class SkillResult(betterproto.Message):
    """SkillResult — outcome of a skill invocation."""

    invocation_id: str = betterproto.string_field(1)
    skill_name: str = betterproto.string_field(2)
    success: bool = betterproto.bool_field(3)
    output: str = betterproto.string_field(4)
    error_message: str = betterproto.string_field(5)
    error_code: str = betterproto.string_field(6)
    timestamp_ms: int = betterproto.int64_field(7)


@dataclass(eq=False, repr=False)
class SkillProgress(betterproto.Message):
    """
    SkillProgress — intermediate progress update during skill execution (CM-06).
    """

    invocation_id: str = betterproto.string_field(1)
    skill_name: str = betterproto.string_field(2)
    progress_percent: float = betterproto.float_field(3)
    status_message: str = betterproto.string_field(4)
    timestamp_ms: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class StreamEnvelope(betterproto.Message):
    """
    StreamEnvelope — wrapper for all objects published into a stream.
     The broker wraps every published object in an envelope for routing and persistence.
    """

    stream_name: str = betterproto.string_field(1)
    object_id: str = betterproto.string_field(2)
    type_url: str = betterproto.string_field(3)
    payload: bytes = betterproto.bytes_field(4)
    publisher_id: str = betterproto.string_field(5)
    published_at_ms: int = betterproto.int64_field(6)
    sequence_number: int = betterproto.uint64_field(7)


@dataclass(eq=False, repr=False)
class TypeRegistration(betterproto.Message):
    """
    TypeRegistration — request to register a custom type in the broker type registry (ADR-004).
    """

    namespace: str = betterproto.string_field(1)
    type_name: str = betterproto.string_field(2)
    descriptor: str = betterproto.string_field(3)
    registered_at_ms: int = betterproto.int64_field(4)


@dataclass(eq=False, repr=False)
class TypeRegistryEntry(betterproto.Message):
    """TypeRegistryEntry — an entry in the broker's type registry."""

    full_name: str = betterproto.string_field(1)
    namespace: str = betterproto.string_field(2)
    type_name: str = betterproto.string_field(3)
    descriptor: str = betterproto.string_field(4)
    is_builtin: bool = betterproto.bool_field(5)


@dataclass(eq=False, repr=False)
class CronEvent(betterproto.Message):
    """
    CronEvent — published by the broker's embedded cron scheduler to a target
     stream when a cron job fires (ADR-012).
     System type (RT-01): broker-internal only, external publish attempts are dropped.
    """

    job_name: str = betterproto.string_field(1)
    """Name of the cron job as declared in the .wh file"""

    action: str = betterproto.string_field(2)
    """Action type: "compact" or "event"""

    schedule: str = betterproto.string_field(3)
    """The cron schedule expression that triggered this event"""

    triggered_at: datetime = betterproto.message_field(4)
    """UTC timestamp when the cron job fired"""

    payload: Dict[str, str] = betterproto.map_field(
        5, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """Optional payload declared in the .wh file cron section"""


@dataclass(eq=False, repr=False)
class TopologyShutdown(betterproto.Message):
    """
    TopologyShutdown — system event published before clean topology stop (CM-01).
     Note: user-facing name avoids "broker" terminology.
    """

    reason: str = betterproto.string_field(1)
    timestamp_ms: int = betterproto.int64_field(2)


@dataclass(eq=False, repr=False)
class StreamCapacityWarning(betterproto.Message):
    """
    StreamCapacityWarning — emitted when WAL approaches max_wal_size_bytes (FM-11, PP-08).
    """

    stream_name: str = betterproto.string_field(1)
    current_size_bytes: int = betterproto.uint64_field(2)
    max_size_bytes: int = betterproto.uint64_field(3)
    usage_percent: float = betterproto.float_field(4)
    timestamp_ms: int = betterproto.int64_field(5)
