# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: wheelhouse/librarian/v1/librarian.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    List,
)

import betterproto


@dataclass(eq=False, repr=False)
class LibraryWriteEvent(betterproto.Message):
    """
    LibraryWriteEvent — carries an end-of-turn conversation segment from a
     client agent to the librarian for write-decision processing (ADR-042).

     One event per conversation turn per agent. Emitted automatically by the
     SDK when WH_LIBRARY_WRITE_STREAM is set. The librarian deserializes and
     feeds the segment to its decision policy.
    """

    event_id: str = betterproto.string_field(1)
    source_agent_id: str = betterproto.string_field(2)
    library_id: str = betterproto.string_field(3)
    conversation_id: str = betterproto.string_field(4)
    timestamp_ms: int = betterproto.int64_field(5)
    segment: List["ConversationMessage"] = betterproto.message_field(6)
    locale: str = betterproto.string_field(7)
    metadata: Dict[str, str] = betterproto.map_field(
        8, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class ConversationMessage(betterproto.Message):
    """
    ConversationMessage — a single message within a conversation segment.
    """

    role: str = betterproto.string_field(1)
    content: str = betterproto.string_field(2)
    timestamp_ms: int = betterproto.int64_field(3)
