"""LibraryWriteEvent and ConversationMessage betterproto definitions.

These match the schema specified in ADR-042:
  proto/wheelhouse/librarian/v1/librarian.proto

Defined as betterproto dataclasses so the SDK deserializer can
decode them from the wire without requiring protoc compilation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

import betterproto


@dataclass(eq=False, repr=False)
class ConversationMessage(betterproto.Message):
    """A single message in a conversation segment."""

    role: str = betterproto.string_field(1)
    """'user' or 'assistant'."""

    content: str = betterproto.string_field(2)
    """Message text."""

    timestamp_ms: int = betterproto.int64_field(3)
    """Unix epoch milliseconds."""


@dataclass(eq=False, repr=False)
class LibraryWriteEvent(betterproto.Message):
    """End-of-turn event carrying a conversation segment to the librarian.

    Emitted by the client agent SDK at end-of-turn when
    WH_LIBRARY_WRITE_STREAM is set. One event per conversation turn per agent.
    """

    event_id: str = betterproto.string_field(1)
    """UUID, generated by the client agent SDK."""

    source_agent_id: str = betterproto.string_field(2)
    """Agent that produced the turn."""

    library_id: str = betterproto.string_field(3)
    """Target Library identifier."""

    conversation_id: str = betterproto.string_field(4)
    """Conversation session identifier."""

    timestamp_ms: int = betterproto.int64_field(5)
    """Unix epoch milliseconds."""

    segment: List[ConversationMessage] = betterproto.message_field(6)
    """The conversation turn(s)."""

    locale: str = betterproto.string_field(7)
    """Detected locale (ISO 639-1), e.g. 'en', 'fr'. Empty if below confidence."""

    metadata: Dict[str, str] = betterproto.map_field(
        8, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    """Extensible metadata."""
